FROM docker.io/spotify/techdocs:v1.2.3
RUN mkdir /output \
    && pip install --no-cache \
        'mkdocs-material' \
        'mkdocs-mermaid-plugin' \
        'mkdocs-mermaid2-plugin' \
        'mkdocs-monorepo-plugin' \
        'mkdocs-diagrams'