apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage-tutorial
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: chart/
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: backstage-tutorial
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
