---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-domain
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: demo
  description: Demonstrate technology concepts and implementation
spec:
  owner: testructer