name: Build and push Docker image (simple)
on:
  push:
    # branches:
    #   - feature/**
    #   - hostfix/**
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc*'
      - '[0-9]+.[0-9]+.[0-9]+-beta*'
      - '[0-9]+.[0-9]+.[0-9]+-alpha*'
      - '[0-9]+.[0-9]+.[0-9]+-hotfix*'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.4
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: yarn build
        run: yarn build:backend
        working-directory: ./

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGES_TOKEN  }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: './'
          file: ./packages/backend/Dockerfile
          push: true
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/backstage:${{ steps.get_version.outputs.VERSION }}
          labels: |
            org.opencontainers.image.description=Docker image generated from the latest Backstage release; this contains what you would get out of the box by running npx @backstage/create-app and building a Docker image from the generated source. This is meant to ease the process of evaluating Backstage for the first time, but also has the severe limitation that there is no way to install additional plugins relevant to your infrastructure.
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.get_version.outputs.VERSION }}